### ISSUE TITLE
Trusted Certificates

### ISSUE THREAD

**Issue by n0xy1** [jmgilman/vaultssh#1]
Hello, 

This is a neat little tool youve created, simplfies the process quite well! 

Unfortunately, i cant seem to get it to connect to my vault. The vaults using a certificate thats signed by a custom CA.

The CA file is trusted in the windows store, and the vault binary works fine when calling using the CLI.

Is there any way i can get vssh to also trust this cert?

**Comment by jmgilman** [comment]
Interesting, the Vault CLI must be integrating with the certificate store somehow. I can look into seeing what that would involve, however, in the meantime you can try setting the [VAULT_CACERT](https://www.vaultproject.io/docs/commands#vault_cacert) environment variable to a local copy of the CA public certificate. The underlying library this tool uses automatically adds any cert found in that environment variable to the local HTTP client. My own internal setup uses an internal CA and this approach works on both Mac and Linux for me.

**Comment by n0xy1** [comment]
Ah nice, that fixed the cert error perfectly! 

Thanks for the quick reply!
